"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
import sys

sys.setrecursionlimit(2000)

VERSION = "0.0.6"

APP = ['main.py']
DATA_FILES = []
OPTIONS = {
    'iconfile': 'icon.icns',
    'plist': {
        'CFBundleName': 'Sportscode',
        'CFBundleShortVersionString': VERSION,
        'CFBundleVersion': VERSION,
        'CFBundleIdentifier': 'com.jamesashenden.sportscode'
    },
    'packages': ['ruamel'],
    'includes': ['ruamel', 'pyannote.audio.pipelines', 'pyannote.audio.models', 'pyannote.audio.models.segmentation', 'speechbrain', 'pyannote.audio.models.embedding']
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
